### ISSUE TITLE
Error on Spigot 1.21

### ISSUE THREAD

**Issue by SlimeDog** [Mr-EmPee/MysticalBarriers#17]
```
>version
[07:42:53] [Server thread/INFO]: This server is running CraftBukkit version 4273-Spigot-34bd42b-2c54749 (MC: 1.21) (Implementing API version 1.21-R0.1-SNAPSHOT)
[07:42:54] [Thread-47/INFO]: You are running the latest version
>version MysticalBarriers
[07:43:26] [Server thread/INFO]: MysticalBarriers version 2.2.2
```
On test server start-up:
```
[07:29:09] [Server thread/INFO]: [MysticalBarriers] Enabling MysticalBarriers v2.2.2
[07:29:09] [Server thread/INFO]: Loaded messages for 1 languages
[07:29:09] [Server thread/INFO]: Connecting to the database...
[07:29:10] [Server thread/ERROR]: Error occurred while enabling MysticalBarriers v2.2.2 (Is it up to date?)
java.lang.RuntimeException: Error while loading of io.github.mr-empee.mysticalbarriers.core.configs.server.CommandsConfig
        at io.github.mr-empee.mysticalbarriers.io.github.empee.lightwire.Component.getInstance(Component.java:46) ~[?:?]
        at io.github.mr-empee.mysticalbarriers.io.github.empee.lightwire.LightWire.lambda$load$2(LightWire.java:63) ~[?:?]
        at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at io.github.mr-empee.mysticalbarriers.io.github.empee.lightwire.LightWire.load(LightWire.java:63) ~[?:?] 
        at io.github.mr-empee.mysticalbarriers.core.MysticalBarriers.onEnable(MysticalBarriers.java:31) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugin(CraftServer.java:575) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4273-Spigot-34bd42b-2c54749]
        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugins(CraftServer.java:489) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4273-Spigot-34bd42b-2c54749]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4273-Spigot-34bd42b-2c54749]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:426) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4273-Spigot-34bd42b-2c54749]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:269) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4273-Spigot-34bd42b-2c54749]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1017) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4273-Spigot-34bd42b-2c54749]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4273-Spigot-34bd42b-2c54749]        at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at io.github.mr-empee.mysticalbarriers.io.github.empee.lightwire.Wirer.execute(Wirer.java:31) ~[?:?]
        at io.github.mr-empee.mysticalbarriers.io.github.empee.lightwire.factories.WiredFactory.get(WiredFactory.java:28) ~[?:?]
        at io.github.mr-empee.mysticalbarriers.io.github.empee.lightwire.Component.getInstance(Component.java:44) ~[?:?]
        ... 15 more
Caused by: java.lang.NoSuchMethodError: 'org.bukkit.command.CommandMap org.bukkit.Server.getCommandMap()'
        at io.github.mr-empee.mysticalbarriers.io.github.empee.colonel.BrigadierManager.getCommandMap(BrigadierManager.java:50) ~[?:?]
        at io.github.mr-empee.mysticalbarriers.io.github.empee.colonel.BrigadierManager.register(BrigadierManager.java:29) ~[?:?]
        at io.github.mr-empee.mysticalbarriers.core.configs.server.CommandsConfig.lambda$new$0(CommandsConfig.java:29) ~[?:?]
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1597) ~[?:?]
        at io.github.mr-empee.mysticalbarriers.core.configs.server.CommandsConfig.<init>(CommandsConfig.java:28) ~[?:?]
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at io.github.mr-empee.mysticalbarriers.io.github.empee.lightwire.Wirer.execute(Wirer.java:31) ~[?:?]
        at io.github.mr-empee.mysticalbarriers.io.github.empee.lightwire.factories.WiredFactory.get(WiredFactory.java:28) ~[?:?]
        at io.github.mr-empee.mysticalbarriers.io.github.empee.lightwire.Component.getInstance(Component.java:44) ~[?:?]
        ... 15 more
```

On otherwise-identical test server running Paper 1.21
```
> version
[07:48:38 INFO]: This server is running Paper version 1.21-109-master@5a5035b (2024-07-23T08:16:30Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-108-73a863b (MC: 1.21)
> version MysticalBarriers
[07:48:43 INFO]: MysticalBarriers version 2.2.2
```
```
[07:46:09] [Paper Plugin Remapper Thread - 3/INFO]: [PluginRemapper] Remapping plugin 'plugins/MysticalBarriers-2.2.2.jar'...
[07:46:10] [Paper Plugin Remapper Thread - 3/INFO]: [PluginRemapper] Done remapping plugin 'plugins/MysticalBarriers-2.2.2.jar' in 986ms.
...
[07:46:51] [Server thread/INFO]: [MysticalBarriers] Loading server plugin MysticalBarriers v2.2.2
...
[07:47:58] [Server thread/INFO]: [MysticalBarriers] Enabling MysticalBarriers v2.2.2
[07:47:58] [Server thread/INFO]: [MysticalBarriers] Loaded messages for 1 languages
[07:47:58] [Server thread/INFO]: [MysticalBarriers] Connecting to the database...
[07:47:59] [Server thread/INFO]: [MysticalBarriers] The command 'mb' has been registered
[07:47:59] [Server thread/INFO]: [MysticalBarriers] Registered 6 listeners
[07:47:59] [Server thread/INFO]: [MysticalBarriers] Established connection to bStats for sending metrics data
[07:47:59] [Server thread/INFO]: [MysticalBarriers] Registered 1 packet listeners
[07:47:59] [Server thread/INFO]: [MysticalBarriers] Registered 1 schedulers
[07:48:43] [Server thread/INFO]: MysticalBarriers version 2.2.2
```

**Comment by Mr-EmPee** [comment]
Hi, ty for reporting the issue. Gonna fix it

**Comment by Mr-EmPee** [comment]
Fixed by #[226b396](https://github.com/Mr-EmPee/MysticalBarriers/commit/226b396bd46c0bb51062dd7fec0f0fe245755208)

**Comment by SlimeDog** [comment]
Thanks. May we have a build/release, please?

**Comment by Mr-EmPee** [comment]
Sure, I'm gonna make a new release as soon as I finish testing it.
